# Generated by Django 3.0.6 on 2020-06-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DCode', models.IntegerField(primary_key=True, serialize=False)),
                ('DName', models.CharField(max_length=20)),
                ('Ddes', models.CharField(max_length=100)),
                ('Dinfo', models.CharField(max_length=3000)),
                ('ImgLink', models.ImageField(default='', upload_to='departments')),
            ],
        ),
    ]
