# Generated by Django 3.0.6 on 2020-06-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=200)),
                ('CDes', models.CharField(max_length=3000)),
                ('DCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department')),
            ],
        ),
    ]
