# Generated by Django 3.0.6 on 2020-06-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('UNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('UName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('RNo', models.AutoField(primary_key=True, serialize=False)),
                ('RName', models.CharField(max_length=100)),
                ('RDes', models.CharField(max_length=200)),
                ('filepath', models.FileField(default='', upload_to='resources')),
                ('CCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
                ('UNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Uploader')),
            ],
        ),
    ]
