# Generated by Django 3.0.6 on 2020-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_resource_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=200)),
                ('Feedback', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='uploader',
            name='UNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
