# Generated by Django 3.0.6 on 2020-06-09 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200602_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('ReqNo', models.AutoField(primary_key=True, serialize=False)),
                ('RDes', models.CharField(max_length=200)),
                ('Userno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
