# Generated by Django 2.2.13 on 2020-12-16 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201216_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploader',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploader',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
