# Generated by Django 2.2.13 on 2020-12-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201216_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='times_visited',
            field=models.IntegerField(default=0),
        ),
    ]
